name: ci-test
on:
  push:
  #   branches:
  #     - develop
  # pull_request:
  #   branches:
  #     - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "setup node"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "lint"
        run: |
         yarn
         yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "setup node"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "build"
        run: |
         yarn
         yarn build
